/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocketJ1939_Frame */

#ifndef _Included_org_isoblue_can_CanSocketJ1939_Frame
#define _Included_org_isoblue_can_CanSocketJ1939_Frame
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
