/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocket_CanFilter */

#ifndef _Included_org_isoblue_can_CanSocket_CanFilter
#define _Included_org_isoblue_can_CanSocket_CanFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
