/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocketJ1939 */

#ifndef _Included_org_isoblue_can_CanSocketJ1939
#define _Included_org_isoblue_can_CanSocketJ1939
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    fetch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocketJ1939_fetch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_initIds
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    setJ1939Filter
 * Signature: ([J[I[I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_setJ1939Filter
  (JNIEnv *, jobject, jlongArray, jintArray, jintArray);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    recvMsg
 * Signature: ()Lorg/isoblue/can/CanSocketJ1939/Frame;
 */
JNIEXPORT jobject JNICALL Java_org_isoblue_can_CanSocketJ1939_recvMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
