/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocketJ1939_Filter */

#ifndef _Included_org_isoblue_can_CanSocketJ1939_Filter
#define _Included_org_isoblue_can_CanSocketJ1939_Filter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_isoblue_can_CanSocketJ1939_Filter_serialVersionUID
#define org_isoblue_can_CanSocketJ1939_Filter_serialVersionUID 20160304001LL
#ifdef __cplusplus
}
#endif
#endif
