/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_j1939_CanSocket */

#ifndef _Included_org_isoblue_j1939_CanSocket
#define _Included_org_isoblue_j1939_CanSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _openSocketRAW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_j1939_CanSocket__1openSocketRAW
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _openSocketBCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_j1939_CanSocket__1openSocketBCM
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _openSocketISOBUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_j1939_CanSocket__1openSocketISOBUS
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _discoverInterfaceIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_j1939_CanSocket__1discoverInterfaceIndex
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _discoverInterfaceName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_isoblue_j1939_CanSocket__1discoverInterfaceName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _bindToSocket
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_j1939_CanSocket__1bindToSocket
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _recvFrame
 * Signature: (I)Lorg/isoblue/j1939/CanSocket/CanFrame;
 */
JNIEXPORT jobject JNICALL Java_org_isoblue_j1939_CanSocket__1recvFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _sendFrame
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_j1939_CanSocket__1sendFrame
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     org_isoblue_j1939_CanSocket
 * Method:    _close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_j1939_CanSocket__1close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
