/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocketJ1939 */

#ifndef _Included_org_isoblue_can_CanSocketJ1939
#define _Included_org_isoblue_can_CanSocketJ1939
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    fetch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocketJ1939_fetch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_initIds
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    setJ1939Filter
 * Signature: ([J[I[I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_setJ1939Filter
  (JNIEnv *, jobject, jlongArray, jintArray, jintArray);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    recvmsg
 * Signature: ()Lorg/isoblue/can/CanSocketJ1939/J1939Message;
 */
JNIEXPORT jobject JNICALL Java_org_isoblue_can_CanSocketJ1939_recvmsg
  (JNIEnv *, jobject);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    bindToSocket
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_bindToSocket
  (JNIEnv *, jobject);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    sendmsg
 * Signature: (Lorg/isoblue/can/CanSocketJ1939/J1939Message;)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_sendmsg
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    bindToAddr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_bindToAddr
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    bindToName
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_bindToName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
