/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocket */

#ifndef _Included_org_isoblue_can_CanSocket
#define _Included_org_isoblue_can_CanSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _openSocketRAW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocket__1openSocketRAW
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _openSocketBCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocket__1openSocketBCM
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _openSocketJ1939
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocket__1openSocketJ1939
  (JNIEnv *, jclass);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _discoverInterfaceIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocket__1discoverInterfaceIndex
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _discoverInterfaceName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_isoblue_can_CanSocket__1discoverInterfaceName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _bindToSocket
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocket__1bindToSocket
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_isoblue_can_CanSocket
 * Method:    _close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocket__1close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
