/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocket_CanFrame */

#ifndef _Included_org_isoblue_can_CanSocket_CanFrame
#define _Included_org_isoblue_can_CanSocket_CanFrame
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
