/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_j1939_CanSocket_CanId_StatusBits */

#ifndef _Included_org_isoblue_j1939_CanSocket_CanId_StatusBits
#define _Included_org_isoblue_j1939_CanSocket_CanId_StatusBits
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
