/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_isoblue_can_CanSocketJ1939 */

#ifndef _Included_org_isoblue_can_CanSocketJ1939
#define _Included_org_isoblue_can_CanSocketJ1939
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    mFetch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_isoblue_can_CanSocketJ1939_mFetch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_isoblue_can_CanSocketJ1939
 * Method:    mSetJ1939filter
 * Signature: (I[J[I[I)V
 */
JNIEXPORT void JNICALL Java_org_isoblue_can_CanSocketJ1939_mSetJ1939filter
  (JNIEnv *, jclass, jint, jlongArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
